extraResources:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: homer
    spec:
      ingressClassName: nginx
      rules:
        - host: "homer.tom.lan"
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: main-homer
                    port:
                      number: 80
  - apiVersion: homer.rajsingh.info/v1alpha1
    kind: Dashboard
    metadata:
      name: main
      namespace: default
    spec:
      replicas: 1
      homerConfig:
        title: "TOM.LAN"
        subtitle: "Dashboard"
        # theme: "default"
        header: true
        footer: false
        logo: "assets/logo.png"
        # logo: "https://raw.githubusercontent.com/rajsinghtech/homer-operator/main/homer/Homer-Operator.png"
