extraResources:
  - apiVersion: homer.rajsingh.info/v1alpha1
    kind: Dashboard
    metadata:
      name: main
      namespace: default
    spec:
      replicas: 1
      homerConfig:
        title: "My Dashboard"
        subtitle: "Welcome to my services"
        theme: "default"
        header: true
        footer: '<p>Powered by Homer Operator</p>'
        logo: "https://raw.githubusercontent.com/rajsinghtech/homer-operator/main/homer/Homer-Operator.png"
