mattermostCR:
  enabled: true
  name: mattermost
  spec:
    # version: 10.10.1
    # replicas: 1
    # size: 100users
    ingress:
      enabled: true
      host: mattermost.tom.lan
    # database:
    #   external:
    #     secret:  <secret-name>
    # fileStore:
    #   external:
    #     bucket:  <bucket-name>
    #     secret:  <secret-name>
    #     url:     s3.amazonaws.com
