# See: https://github.com/mattermost/mattermost-operator/blob/master/docs/examples/mattermost_full.yaml
mattermost:
  enabled: true
  name: mattermost
  spec:
    ingress:
      enabled: true
      host: mattermost.tom.lan
    database:
      external:
        secret: mattermost-database
    fileStore:
      external:
        url: minio:443
        bucket: mattermost
        secret: mattermost-filestore
