crds:
  enabled: true

extraObjects:
  - |
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: hawk-acme
    spec:
      acme:
        # email: user@example.com
        server: https://ca.tom.lan/acme/acme/directory
        privateKeySecretRef:
          name: hawk-acme-account-key
        solvers:
          - http01:
              ingress:
                ingressClassName: traefik
  # - apiVersion: v1
  #   kind: ConfigMap
  #   metadata:
  #     name: hawk-ca
  #   data:
  #     internal-ca.pem: |
  #       -----BEGIN CERTIFICATE-----
  #       MIIBczCCARmgAwIBAgIQMWZZ86a+yvmQoeLS4gM/4jAKBggqhkjOPQQDAjAXMRUw
  #       EwYDVQQDEwxIYXdrIFJvb3QgQ0EwIBcNMjUxMjA3MjExNDE0WhgPMjEyNTExMTMy
  #       MTE0MTRaMBcxFTATBgNVBAMTDEhhd2sgUm9vdCBDQTBZMBMGByqGSM49AgEGCCqG
  #       SM49AwEHA0IABKBS14OgDb7KHLWjiMrIFC7yKI1WAWn9O+z90f9FsCfTQ6mar3ga
  #       4OkxKZeK3U3x3TG9GR/X3kqNspZRXBNb5S+jRTBDMA4GA1UdDwEB/wQEAwIBBjAS
  #       BgNVHRMBAf8ECDAGAQH/AgEBMB0GA1UdDgQWBBTpufF7DQTmajB0dufPWJ09JNhN
  #       FDAKBggqhkjOPQQDAgNIADBFAiEAkQpHG9cd0tjRoypJgvNu8CmsvPaK166VBXZK
  #       HCt9B2ICICJF/g/SD/kL0LCJ0g7ZlH0rdTFYC21UxDEc8r4dzMXg
  #       -----END CERTIFICATE-----
